In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('Housing.csv')
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [2]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [33]:
df['price_per_area'] = df['price'] / df['area']
df['area_per_bedroom'] = df['area'] / df['bedrooms']
df['area_per_bathroom'] = df['area'] / df['bathrooms']
df['stories_area'] = df['stories'] * df['area']
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_per_area,area_per_bedroom,area_per_bathroom,stories_area,area_bedrooms,area_bathrooms,bed_bath_ratio
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,1792.452830,1855.000000,3710.0,22260,29680,14840,1.333333
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished,1367.187500,2240.000000,2240.0,35840,35840,35840,0.800000
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,1229.919679,3320.000000,4980.0,19920,29880,19920,1.000000
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,1628.666667,1875.000000,3750.0,15000,30000,15000,1.333333
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished,1537.735849,1855.000000,7420.0,14840,29680,7420,2.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished,606.666667,1500.000000,3000.0,3000,6000,3000,1.000000
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished,736.312500,800.000000,2400.0,2400,7200,2400,1.500000
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished,483.425414,1810.000000,3620.0,3620,7240,3620,1.000000
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished,601.374570,970.000000,2910.0,2910,8730,2910,1.500000
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished,454.545455,1283.333333,3850.0,7700,11550,3850,1.500000

In [34]:
from sklearn.model_selection import train_test_split
X = pd.get_dummies(df.drop("price", axis=1), drop_first=True)
y = df["price"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [35]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [36]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mae = mean_absolute_error(y_test, y_pred)
mae

570464.0453058536

In [30]:
mse = mean_squared_error(y_test, y_pred)
mse

572529995726.0284

In [37]:
rmse = np.sqrt(mse)
rmse

np.float64(756657.1189951419)

In [38]:
r2 = r2_score(y_test, y_pred)
r2

0.867955220739561

In [13]:
new_house = {
    "area": 3000,
    "bedrooms": 3,
    "bathrooms": 2,
    "stories": 2,
    "mainroad": "yes",
    "guestroom": "no",
    "basement": "yes",
    "hotwaterheating": "no",
    "airconditioning": "yes",
    "parking": 2,
    "prefarea": "yes",
    "furnishingstatus": "furnished"
}

new_df = pd.DataFrame([new_house])
new_df_encoded = pd.get_dummies(new_df)
for col in X_train.columns:
    if col not in new_df_encoded.columns:
        new_df_encoded[col] = 0
new_df_encoded = new_df_encoded[X_train.columns]
predicted_price = model.predict(new_df_encoded)
predicted_price

array([13953.11927831])